# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 02:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_goodsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        )


    ]
